# استخدام نسخة خفيفة من بايثون
FROM python:3.11-slim

# إعداد مجلد العمل
WORKDIR /app

# نسخ ملف المتطلبات وتثبيتها
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# نسخ كود البوت
COPY bot.py .

# تشغيل البوت
CMD ["python", "bot.py"]
